### ISSUE TITLE
How to query ext* partitions in Windows?

### ISSUE THREAD

**Issue by kumarharsh** [resin-io/drivelist#16] opened 2015-08-25 05:49 UTC
When I'm using the example given in the readme in Windows, I'm not able to see the ext4 partition of my ubuntu. Is there a way to list those too?

**Comment by jviotti** [comment] 2015-08-25 13:52
Hi @kumarharsh , 

- Can you access the Ubuntu partition from Windows from the file manager? I don't think Windows reads ext4 partitions out of the box, and that should be why it's not appearing on `drivelist`.

- What happens when you run the following command in `cmd.exe` or Powershell?:

```sh
> wmic diskdrive list brief
```

Is the Ubuntu partition being listed there?

**Comment by kumarharsh** [comment] 2015-08-25 14:05
No, it doesn't. I'd thought it'd offer some lower level API to do that... something like what ext2read offers.

**Comment by jviotti** [comment] 2015-08-25 14:10
@kumarharsh In that case there's not much we can do from `drivelist` standpoint, since it relies on the operating system having support for it.

I'm not a Windows user (@Page- might be able to help here), but I believe that you can install ext drivers to bring support at the operating system level, which should result in the drives get listed in `drivelist`.

**Comment by jviotti** [comment] 2015-08-25 14:11
@kumarharsh A bit of googling leads me to http://www.paragon-drivers.com/extfs-windows/.

**Comment by jviotti** [comment] 2015-11-18 16:23
Closing since the issue is not `drivelist`.

**Closed by jviotti** 2015-11-18 16:23 UTC
Labels: question
